<div class="row">
    <div class="col-md-12">
        <h3>New Task</h3>
    </div>
</div>
<div class="row py-3">
    <div class="col-md-12">
        <?php if (isset($errorMessages) && is_array($errorMessages) && count($errorMessages)) {?>
            <div class="alert alert-danger" role="alert">
                <?php foreach ($errorMessages as $message) {?>
                    <?= $message . '<br />';?>
                <?php }?>
            </div>
        <?php } else if (isset($successMessage)) {?>
            <div class="alert alert-success" role="alert"><?= $successMessage; ?></div>
        <?php }?>
            
        <form id="frmAddTask" action="/task/add" method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <label for="user_name">User Name <span class="text-danger">*</span></label>
                <input type="user_name" name="user_name" class="form-control" id="user_name" placeholder="John Doe" value="<?php if (isset($userName)) { echo $userName; }?>">
            </div>
            <div class="form-group">
                <label for="email">Email <span class="text-danger">*</span></label>
                <input type="email" name="email" class="form-control" id="email" placeholder="name@example.com" value="<?php if (isset($email)) { echo $email; }?>">
            </div>
            <div class="form-group">
                <label for="body">Body <span class="text-danger">*</span></label>
                <textarea name="body" class="form-control" id="body" rows="3"><?php if (isset($body)) { echo $body; }?></textarea>
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-info" href="#" role="button" onclick="javascript:preview(); return false;">Preview</a>
            <a class="btn btn-secondary" href="/" role="button">Return</a>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="previewModal" tabindex="-1" role="dialog" aria-labelledby="previewModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="previewModalTitle">Task Preview</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="boxLoadImageError" style="display:none;" class="alert alert-danger" role="alert"></div>
                <div id="boxTaskPreview"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    function preview()
    {
        var userName = $('#user_name').val();
        var email = $('#email').val();
        var body = $('#body').val();
        
        if (!userName || !email || !body) {
            alert('Enter required fields');
            return;
        }
        
        $("#previewModal #boxTaskPreview").html('<div class="text-center"><i class="fa fa-spinner fa-spin"></i></div>');
        $('#previewModal').modal('show');

        var formData = new FormData();
        formData.append( 'user_name', userName );
        formData.append( 'email', email );
        formData.append( 'body', body );


        // Set up the request.
        var xhr = new XMLHttpRequest();

        // Open the connection.
        xhr.open('POST', '/task/preview/', true);

        xhr.onerror = function() { alert("Error Status: " + xhr.statusText); };
        // Set up a handler for when the request finished.
        xhr.onload = function () {
            if (xhr.status === 200) {
                $("#previewModal #boxTaskPreview").html(xhr.response);
            } else {
                $("#boxLoadImageError").html("Error :\n\n"+xhr.statusText).show();
            }
        };

        // Send the Data.
        xhr.send(formData);
    }
//]]>
</script>