<div class="row">
    <div class="col-md-12">
        <h3>Edit Task #<?= $task['id']; ?></h3>
    </div>
</div>
<div class="row py-3">
    <div class="col-md-12">
        <?php if (isset($errorMessages) && is_array($errorMessages) && count($errorMessages)) {?>
            <div class="alert alert-danger" role="alert">
                <?php foreach ($errorMessages as $message) {?>
                    <?= $message . '<br />';?>
                <?php }?>
            </div>
        <?php } else if (isset($successMessage)) {?>
            <div class="alert alert-success" role="alert"><?= $successMessage; ?></div>
        <?php }?>
            
        <form id="frmTasksList" action="/task/edit" method="POST">
            <input type="hidden" name="id" value="<?= $task['id']; ?>">
            <div class="form-group">
                <label for="user_name">User Name</label>
                <input type="user_name" name="user_name" class="form-control" id="user_name" disabled value="<?= $task['user_name'];?>">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" class="form-control" id="email" disabled value="<?= $task['email'];?>">
            </div>
            <div class="form-group">
                <label for="status">Status</label>
                <select class="form-control" name="status" id="status">
                    <?php foreach ($listStatuses as $status) {?>
                        <option value="<?= $status; ?>" <?php if ($task['status'] == $status) { echo 'selected'; } ?>><?= $status; ?></option>
                    <?php }?>
                </select>
            </div>
            <div class="form-group">
                <label for="body">Body <span class="text-danger">*</span></label>
                <textarea name="body" class="form-control" id="body" rows="3"><?= $task['body']; ?></textarea>
            </div>
            
            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-secondary" href="/" role="button">Return</a>
        </form>
    </div>
</div>