<?php if (isset($errorMessage)) {?>
    <div class="alert alert-danger" role="alert">
        <?= $errorMessage;?>
    </div>
<?php } else {?>
    <div class="row py-3">
        <div class="col-md-12"> 
            <table class="table table-user-information">
                <tbody>
                    <tr>
                        <td>User Name</td>
                        <td><?= $userName; ?></td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td><?= $email; ?></td>
                    </tr>
                    <tr>
                        <td>Body</td>
                        <td><?= $body; ?></td>
                    </tr>
<!--                    <tr>-->
<!--                        <td>Image</td>-->
<!--                        <td>-->
<!--                            --><?php //if (isset($image)) {?>
<!--                                <img src="--><?//= $image;?><!--" />-->
<!--                            --><?php //} else {?>
<!--                                no image-->
<!--                            --><?php //}?>
<!--                        </td>-->
<!--                    </tr>-->
                </tbody>
            </table>
        </div>
    </div>
<?php }?>

