<div class="row">
    <div class="col-md-12">
        <h3>Log In</h3>
    </div>
</div>
<div class="row py-3">
    <div class="col-md-12">
        <?php if (isset($errorMessage)) {?>
            <div class="alert alert-danger" role="alert"><?= $errorMessage;?></div>
        <?php }?>
        <form id="frmLogin" action="/user/login" method="POST">
            <div class="form-group">
                <label for="name">User Name</label>
                <input type="text" name="name" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter name" value="<?php if (isset($name)) { echo $name; }?>">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Log In</button>
        </form>
    </div>
</div>