<?php $previousPage = ($page > 1) ? $page - 1 : 0;?>
<?php $nextPage     = ($page < $totalPages) ? $page + 1 : 0;?>

<?php
    $url = "/?";
    if ($page) $url .= "page=%d&";
    if ($rowsPerPage) $url .= "rowsPerPage={$rowsPerPage}&";
    if ($sortField) $url .= "sortField={$sortField}&";
    if ($sortDirection) $url .= "sortDirection={$sortDirection}";
    $url = trim($url, '&');
?>

<nav aria-label="Page navigation">
    <ul class="pagination">
        <?php if ($previousPage) {?>
            <li class="page-item"><a class="page-link" href="<?= sprintf($url, $previousPage)?>">Previous</a></li>
        <?php } else {?>
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
        <?php }?>

        <?php if ($totalPages < 13) { /* « Previous  1 2 3 4 5 6 7 8 9 10 11 12  Next » */ ?>

            <?php for ($i = 1; $i <= $totalPages; $i++): ?>
                <?php if ($i == $page) { ?>
                    <li class="page-item active">
                        <span class="page-link"><?php echo $i ?><span class="sr-only">(current)</span></span>
                    </li>
                <?php } else { ?>
                    <li class="page-item">
                        <a class="page-link" href="<?= sprintf($url, $i)?>"><?php echo $i ?></a>
                    </li>
                <?php } ?>
            <?php endfor ?>

        <?php } else if ($page < 9) { /* « Previous  1 2 3 4 5 6 7 8 9 10 … 25 26  Next » */ ?>

            <?php for ($i = 1; $i <= 10; $i++) { ?>
                <?php if ($i == $page) { ?>
                    <li class="page-item active">
                        <span class="page-link"><?php echo $i ?><span class="sr-only">(current)</span></span>
                    </li>
                <?php } else { ?>
                    <li class="page-item">
                        <a class="page-link" href="<?= sprintf($url, $i)?>"><?php echo $i ?></a>
                    </li>
                <?php } ?>
            <?php } ?>

            &hellip;

            <li class="page-item"><a class="page-link" href="<?= sprintf($url, $totalPages - 1)?>"><?php echo $totalPages - 1 ?></a></li>
            <li class="page-item"><a class="page-link" href="<?= sprintf($url, $totalPages)?>"><?php echo $totalPages ?></a></li>

        <?php } else if ($page > $totalPages - 8) { /* « Previous  1 2 … 17 18 19 20 21 22 23 24 25 26  Next » */ ?>

            <li class="page-item"><a class="page-link" href="<?= sprintf($url, 1)?>">1</a></li>
            <li class="page-item"><a class="page-link" href="<?= sprintf($url, 2)?>">2</a></li>

            &hellip;

            <?php for ($i = $totalPages - 9; $i <= $totalPages; $i++) { ?>
                <?php if ($i == $page) { ?>
                    <li class="page-item active">
                        <span class="page-link"><?php echo $i ?><span class="sr-only">(current)</span></span>
                    </li>
                <?php } else { ?>
                    <li class="page-item">
                        <a class="page-link" href="<?= sprintf($url, $i)?>"><?php echo $i ?></a>
                    </li>
                <?php } ?>
            <?php } ?>

        <?php } else { /* « Previous  1 2 … 5 6 7 8 9 10 11 12 13 14 … 25 26  Next » */ ?>

            <li class="page-item"><a class="page-link" href="<?= sprintf($url, 1)?>">1</a></li>
            <li class="page-item"><a class="page-link" href="<?= sprintf($url, 2)?>">2</a></li>

            &hellip;

            <?php for ($i = $page - 5; $i <= $page + 5; $i++) { ?>
                <?php if ($i == $page) { ?>
                    <li class="page-item active">
                        <span class="page-link"><?php echo $i ?><span class="sr-only">(current)</span></span>
                    </li>
                <?php } else { ?>
                    <li class="page-item">
                        <a class="page-link" href="<?= sprintf($url, $i)?>"><?php echo $i ?></a>
                    </li>
                <?php } ?>
            <?php } ?>

            &hellip;

            <li class="page-item"><a class="page-link" href="<?= sprintf($url, $totalPages - 1)?>"><?php echo $totalPages - 1 ?></a></li>
            <li class="page-item"><a class="page-link" href="<?= sprintf($url, $totalPages)?>"><?php echo $totalPages ?></a></li>

        <?php } ?>

        <?php if ($nextPage) {?>
            <li class="page-item"><a class="page-link" href="<?= sprintf($url, $nextPage)?>">Next</a></li>
        <?php } else {?>
            <li class="page-item disabled"><span class="page-link">Next</span></li>
        <?php }?>
    </ul>
</nav>